version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jdr_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jdr_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_SSL_MODE: DISABLED
    ports:
     - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: php:8.2-apache
    container_name: jdr_web
    ports:
      - "8080:80"
    volumes:
    - ./:/var/www/html

    depends_on:
      - db

volumes:
  db_data: